export const operationTypeOptions = [
  { label: "登录成功", value: "LOGIN_SUCCESS" },
  { label: "登录失败", value: "LOGIN_FAILED" },
  { label: "创建用户", value: "CREATE_USER" },
  { label: "修改用户", value: "UPDATE_USER" },
  { label: "新增后台账号", value: "CREATE_ACCOUNT" },
  { label: "编辑后台账号", value: "UPDATE_ACCOUNT" },
  { label: "启用后台账号", value: "ENABLE_ACCOUNT" },
  { label: "停用后台账号", value: "DISABLE_ACCOUNT" },
  { label: "重置后台账号密码", value: "RESET_ACCOUNT_PASSWORD" },
  { label: "开通管家账号", value: "CREATE_BUTLER_ACCOUNT" },
  { label: "启用管家账号", value: "ENABLE_BUTLER_ACCOUNT" },
  { label: "停用管家账号", value: "DISABLE_BUTLER_ACCOUNT" },
  { label: "重置管家账号密码", value: "RESET_BUTLER_ACCOUNT_PASSWORD" },
  { label: "小程序自动登录成功", value: "MINIPROGRAM_AUTO_LOGIN_SUCCESS" },
  { label: "小程序登录失败", value: "MINIPROGRAM_LOGIN_FAILED" },
  { label: "小程序账号绑定成功", value: "MINIPROGRAM_BIND_SUCCESS" },
  { label: "小程序账号绑定失败", value: "MINIPROGRAM_BIND_FAILED" },
  { label: "小程序账号解绑", value: "MINIPROGRAM_UNBIND" },
  { label: "后台解绑小程序账号", value: "ADMIN_UNBIND_MINIPROGRAM" },
  { label: "创建酒店", value: "CREATE_HOTEL" },
  { label: "修改酒店", value: "UPDATE_HOTEL" },
  { label: "新增房型", value: "CREATE_HOTEL_ROOM_TYPE" },
  { label: "修改房型", value: "UPDATE_HOTEL_ROOM_TYPE" },
  { label: "停用房型", value: "DELETE_HOTEL_ROOM_TYPE" },
  { label: "创建管家", value: "CREATE_BUTLER" },
  { label: "修改管家", value: "UPDATE_BUTLER" },
  { label: "创建订单", value: "CREATE_ORDER" },
  { label: "修改订单", value: "UPDATE_ORDER" },
  { label: "派单", value: "DISPATCH_ORDER" },
  { label: "改派", value: "REASSIGN_ORDER" },
  { label: "订单状态变更", value: "ORDER_STATUS_CHANGE" },
  { label: "订单评价状态变更", value: "ORDER_REVIEW_STATUS_CHANGE" },
  { label: "处理过期派单", value: "RESOLVE_OVERDUE_ASSIGNMENT" },
  { label: "管家确认接单", value: "BUTLER_CONFIRM_ORDER" },
  { label: "管家拒单", value: "BUTLER_REJECT_ORDER" },
  { label: "已接到客人", value: "BUTLER_PICKED_GUEST" },
  { label: "完成服务", value: "BUTLER_COMPLETE_ORDER" },
  { label: "后台确认服务完成", value: "COMPLETE_ASSIGNMENT_BY_BACKOFFICE" },
  { label: "取消派单", value: "CANCEL_DISPATCH_ASSIGNMENT" },
  { label: "提交请假", value: "BUTLER_SUBMIT_LEAVE" },
  { label: "撤销请假", value: "BUTLER_CANCEL_LEAVE" },
  { label: "审核通过请假", value: "APPROVE_LEAVE" },
  { label: "驳回请假", value: "REJECT_LEAVE" },
  { label: "创建业务配置", value: "CREATE_SYSTEM_DICT" },
  { label: "修改业务配置", value: "UPDATE_SYSTEM_DICT" },
  { label: "创建异常记录", value: "CREATE_ABNORMAL_RECORD" },
  { label: "更新异常记录", value: "UPDATE_ABNORMAL_RECORD" },
  { label: "处理异常记录", value: "RESOLVE_ABNORMAL_RECORD" },
  { label: "修改结算状态", value: "UPDATE_SETTLEMENT_STATUS" },
  { label: "查看个人统计", value: "VIEW_BUTLER_STATISTICS" },
  { label: "查看后台管家统计", value: "VIEW_BUTLER_STATISTICS_REPORT" },
  { label: "导出订单明细", value: "EXPORT_ORDERS" },
  { label: "导出拒单记录", value: "EXPORT_REJECTIONS" },
  { label: "导出请假记录", value: "EXPORT_LEAVES" },
  { label: "导出评价统计", value: "EXPORT_REVIEWS" },
  { label: "导出财务总表", value: "EXPORT_FINANCE_REPORT" },
  { label: "导出酒店统计", value: "EXPORT_HOTEL_STATISTICS" },
  { label: "导出管家服务明细", value: "EXPORT_BUTLER_SERVICES" },
  { label: "导出管家统计", value: "EXPORT_BUTLER_STATISTICS" }
];

export const targetTypeOptions = [
  { label: "用户", value: "User" },
  { label: "酒店", value: "Hotel" },
  { label: "酒店房型", value: "HotelRoomType" },
  { label: "管家", value: "Butler" },
  { label: "订单", value: "ServiceOrder" },
  { label: "订单分配", value: "OrderButlerAssignment" },
  { label: "请假记录", value: "ButlerLeave" },
  { label: "服务评价", value: "ServiceReview" },
  { label: "业务配置", value: "SystemDict" },
  { label: "异常记录", value: "AbnormalRecord" },
  { label: "管家统计", value: "ButlerStatistics" },
  { label: "导出记录", value: "FinanceExport" }
];

export function getOperationTypeLabel(value: string) {
  return operationTypeOptions.find((item) => item.value === value)?.label ?? value;
}

export function getTargetTypeLabel(value: string) {
  return targetTypeOptions.find((item) => item.value === value)?.label ?? value;
}
